import { createHash } from "crypto";
import { Address } from "@stellar/stellar-sdk";

/**
 * TypeScript half of the Merkle-drop scheme implemented in
 * `contracts/voting-rewards/src/merkle.rs`.
 *
 * Every byte of this file is a cross-language contract with that module: if
 * the two disagree by a single bit, every proof this backend serves is
 * rejected on-chain. `backend/src/__tests__/voting-rewards-merkle.test.ts`
 * pins both sides to the same golden vectors, generated by the Rust
 * `golden_merkle_vectors` test — change one, and the other fails.
 */

/** A single `(address, amount)` pair destined for one epoch's tree. */
export interface RewardEntry {
  address: string;
  amount: bigint;
}

export interface MerkleTree {
  /** Hex-encoded root, or `null` for an empty (zero-participation) epoch. */
  root: string | null;
  /** Entries in the exact leaf order the tree was built from. */
  entries: RewardEntry[];
  /** Hex-encoded leaves, index-aligned with {@link entries}. */
  leaves: string[];
  /** Hex-encoded sibling path for the leaf at `index`. */
  proofFor(index: number): string[];
  /** Hex-encoded sibling path for `address`, or `null` if it has no leaf. */
  proofForAddress(address: string): string[] | null;
}

function sha256(data: Buffer): Buffer {
  return createHash("sha256").update(data).digest();
}

/** `u64` little-endian, matching Rust's `u64::to_le_bytes`. */
function u64le(value: bigint): Buffer {
  const buf = Buffer.alloc(8);
  buf.writeBigUInt64LE(BigInt.asUintN(64, value));
  return buf;
}

/** `i128` little-endian two's complement, matching Rust's `i128::to_le_bytes`. */
function i128le(value: bigint): Buffer {
  const unsigned = BigInt.asUintN(128, value);
  const buf = Buffer.alloc(16);
  buf.writeBigUInt64LE(unsigned & 0xffffffffffffffffn, 0);
  buf.writeBigUInt64LE(unsigned >> 64n, 8);
  return buf;
}

/**
 * `sha256(claimant || epoch_id || amount)`, the leaf the contract's `claim`
 * reconstructs from its own arguments.
 *
 * `claimant` is encoded as the XDR of its `ScVal::Address` — exactly what
 * `Address::to_xdr` emits on the Rust side — so an account address and a
 * contract address of the same underlying bytes can never collide.
 */
export function computeLeaf(address: string, epochId: bigint, amount: bigint): Buffer {
  const claimant = Address.fromString(address).toScVal().toXDR();
  return sha256(Buffer.concat([claimant, u64le(epochId), i128le(amount)]));
}

/**
 * `sha256(min(a, b) || max(a, b))`.
 *
 * Sorting the pair is what lets a proof be a bare list of siblings with no
 * left/right flags, which is the shape `claim(..., proof: Vec<BytesN<32>>)`
 * expects.
 */
export function hashPair(a: Buffer, b: Buffer): Buffer {
  return Buffer.compare(a, b) <= 0
    ? sha256(Buffer.concat([a, b]))
    : sha256(Buffer.concat([b, a]));
}

function nextLevel(level: Buffer[]): Buffer[] {
  const next: Buffer[] = [];
  for (let i = 0; i < level.length; i += 2) {
    // An odd trailing node is promoted unchanged rather than paired with
    // itself — same rule as the Rust reference builder.
    next.push(i + 1 < level.length ? hashPair(level[i], level[i + 1]) : level[i]);
  }
  return next;
}

/**
 * Build an epoch's Merkle tree.
 *
 * Entries are sorted by address first, so the tree (and therefore the root
 * published on-chain) is a pure function of the `(address, amount)` set and
 * never of the order the database happened to return rows in.
 *
 * An empty entry list is a valid input, not an error: an epoch in which
 * nobody voted yields `root: null` and no claims, and is still published
 * on-chain with a zero allocation so the epoch history stays contiguous.
 */
export function buildMerkleTree(entries: RewardEntry[], epochId: bigint): MerkleTree {
  const sorted = [...entries].sort((a, b) => (a.address < b.address ? -1 : a.address > b.address ? 1 : 0));
  const leaves = sorted.map((e) => computeLeaf(e.address, epochId, e.amount));

  const levels: Buffer[][] = [];
  if (leaves.length > 0) {
    let level = leaves;
    levels.push(level);
    while (level.length > 1) {
      level = nextLevel(level);
      levels.push(level);
    }
  }

  const proofFor = (index: number): string[] => {
    if (index < 0 || index >= sorted.length) {
      throw new RangeError(`leaf index ${index} out of range (${sorted.length} leaves)`);
    }
    const proof: string[] = [];
    let idx = index;
    for (let depth = 0; depth < levels.length - 1; depth++) {
      const level = levels[depth];
      const sibling = idx % 2 === 0 ? idx + 1 : idx - 1;
      if (sibling < level.length) proof.push(level[sibling].toString("hex"));
      idx = Math.floor(idx / 2);
    }
    return proof;
  };

  return {
    root: leaves.length > 0 ? levels[levels.length - 1][0].toString("hex") : null,
    entries: sorted,
    leaves: leaves.map((l) => l.toString("hex")),
    proofFor,
    proofForAddress(address: string) {
      const index = sorted.findIndex((e) => e.address === address);
      return index === -1 ? null : proofFor(index);
    },
  };
}

/** Fold `leaf` up through `proof` and compare against `root` — the exact check `claim` performs. */
export function verifyProof(leaf: Buffer, proof: string[], root: string): boolean {
  const computed = proof.reduce(
    (acc, sibling) => hashPair(acc, Buffer.from(sibling, "hex")),
    leaf,
  );
  return computed.toString("hex") === root;
}
