import { Keypair } from "@stellar/stellar-sdk";
import {
  buildMerkleTree,
  computeLeaf,
  hashPair,
  verifyProof,
} from "../voting-rewards/merkle";

/**
 * Golden vectors generated by the Rust reference test
 * `golden_merkle_vectors` in `contracts/voting-rewards/src/tests.rs`.
 *
 * This is the cross-language pin: the contract's `claim` rebuilds the leaf
 * from its own arguments and folds the proof itself, so if this file and
 * `contracts/voting-rewards/src/merkle.rs` disagree by a single byte, every
 * proof this backend serves would be rejected on-chain. Both sides assert
 * against the same constants — change one and the other fails.
 */
const GOLDEN_EPOCH_ID = 7n;

const GOLDEN_ENTRIES = [
  { address: "GA3I6MVQC2EXERDKLVWNFGGYEHII5ZVWFS4ZUQGKAP3XRJWR7P5FUGQJ", amount: 250_000n },
  { address: "GAKXV3A3HTPD6VG63VDC7YHEGXFUW64PGVOKPIOYMIXLZRAXLQMG22CN", amount: 42n },
  { address: "GAS6QC6USQHIUKQH4EY6KC62IN7Q4NX3M73L3PI7YWQZYHDFQCTB4LZY", amount: 1n },
  { address: "GBVOQAK3E3EW5ULNEE6R5E63HKSGPH7AWPM75CTWI5IES7JPI54L5M57", amount: 999_999_999n },
  { address: "GCAY5IGF2CMHCG56BR7FBJZOMRGP7UJKSOESULXEJ5XHB3U4ELYJG4IC", amount: 7_500n },
];

const GOLDEN_LEAVES = [
  "0bf621a13487fe1aef039095a25b40ee9bdfb526a4d8054f28ae10adc8041ba0",
  "1fce2eed9c80e1236b401ba2ee8c066884e30c087d319c92931be01e9bd4ea71",
  "9cb87f75012885e109a0b81775abf2caf209889fc96d2bd0aef10c8568b9858e",
  "74094b403e4eceefca4967acc71ea28977f617335555778ebbcc86e1999616ee",
  "19fd2f38ad9e87bf4436f675ea354c32c3d399beb72037580b1c74f7ec80e3ca",
];

const GOLDEN_ROOT = "09f6d53699eda9c424859b1cabf7b12279ca966e0c45e9e49d1fc47e1867bd35";

const GOLDEN_PROOFS = [
  [
    "1fce2eed9c80e1236b401ba2ee8c066884e30c087d319c92931be01e9bd4ea71",
    "984fbfd69220764e60b0539ae477e6b1f7419d9ccd0b7655f8f25d27070a8eb2",
    "19fd2f38ad9e87bf4436f675ea354c32c3d399beb72037580b1c74f7ec80e3ca",
  ],
  [
    "0bf621a13487fe1aef039095a25b40ee9bdfb526a4d8054f28ae10adc8041ba0",
    "984fbfd69220764e60b0539ae477e6b1f7419d9ccd0b7655f8f25d27070a8eb2",
    "19fd2f38ad9e87bf4436f675ea354c32c3d399beb72037580b1c74f7ec80e3ca",
  ],
  [
    "74094b403e4eceefca4967acc71ea28977f617335555778ebbcc86e1999616ee",
    "8774ae760b584499953da69296ccb9eca937d3bdf8866420c21806cc3aa849e0",
    "19fd2f38ad9e87bf4436f675ea354c32c3d399beb72037580b1c74f7ec80e3ca",
  ],
  [
    "9cb87f75012885e109a0b81775abf2caf209889fc96d2bd0aef10c8568b9858e",
    "8774ae760b584499953da69296ccb9eca937d3bdf8866420c21806cc3aa849e0",
    "19fd2f38ad9e87bf4436f675ea354c32c3d399beb72037580b1c74f7ec80e3ca",
  ],
  ["6ea80d6c6732a9803a42f6946621bc2169894c95f12aaa15f78f6388611f14ac"],
];

describe("voting rewards merkle (issue #1011)", () => {
  describe("golden cross-check against the Rust implementation", () => {
    it("reproduces every leaf hash byte-for-byte", () => {
      GOLDEN_ENTRIES.forEach((entry, index) => {
        expect(computeLeaf(entry.address, GOLDEN_EPOCH_ID, entry.amount).toString("hex")).toBe(
          GOLDEN_LEAVES[index],
        );
      });
    });

    it("reproduces the root", () => {
      expect(buildMerkleTree(GOLDEN_ENTRIES, GOLDEN_EPOCH_ID).root).toBe(GOLDEN_ROOT);
    });

    it("reproduces the proof for every leaf, not just the first and last", () => {
      const tree = buildMerkleTree(GOLDEN_ENTRIES, GOLDEN_EPOCH_ID);
      GOLDEN_ENTRIES.forEach((_, index) => {
        expect(tree.proofFor(index)).toEqual(GOLDEN_PROOFS[index]);
      });
    });

    it("produces a root independent of the order entries arrive in", () => {
      const shuffled = [GOLDEN_ENTRIES[3], GOLDEN_ENTRIES[0], GOLDEN_ENTRIES[4], GOLDEN_ENTRIES[2], GOLDEN_ENTRIES[1]];
      expect(buildMerkleTree(shuffled, GOLDEN_EPOCH_ID).root).toBe(GOLDEN_ROOT);
    });
  });

  describe("proof generation", () => {
    // Odd sizes exercise the promoted trailing node, which is where a
    // Merkle implementation most often diverges from its counterpart.
    for (const size of [1, 2, 3, 4, 5, 6, 7, 8, 9, 17]) {
      it(`verifies every leaf's proof in a ${size}-address tree`, () => {
        const entries = Array.from({ length: size }, (_, i) => ({
          address: Keypair.random().publicKey(),
          amount: BigInt(i + 1) * 1_000n,
        }));

        const tree = buildMerkleTree(entries, GOLDEN_EPOCH_ID);

        tree.entries.forEach((entry, index) => {
          const leaf = computeLeaf(entry.address, GOLDEN_EPOCH_ID, entry.amount);
          expect(verifyProof(leaf, tree.proofFor(index), tree.root!)).toBe(true);
        });
      });
    }

    it("rejects a proof once the amount is tampered with", () => {
      const tree = buildMerkleTree(GOLDEN_ENTRIES, GOLDEN_EPOCH_ID);
      const tampered = computeLeaf(GOLDEN_ENTRIES[0].address, GOLDEN_EPOCH_ID, 999_999n);

      expect(verifyProof(tampered, tree.proofFor(0), tree.root!)).toBe(false);
    });

    it("rejects one claimant's proof presented for another claimant", () => {
      const tree = buildMerkleTree(GOLDEN_ENTRIES, GOLDEN_EPOCH_ID);
      const otherLeaf = computeLeaf(
        GOLDEN_ENTRIES[1].address,
        GOLDEN_EPOCH_ID,
        GOLDEN_ENTRIES[0].amount,
      );

      expect(verifyProof(otherLeaf, tree.proofFor(0), tree.root!)).toBe(false);
    });

    it("binds a leaf to its epoch", () => {
      const tree = buildMerkleTree(GOLDEN_ENTRIES, GOLDEN_EPOCH_ID);
      const wrongEpoch = computeLeaf(
        GOLDEN_ENTRIES[0].address,
        GOLDEN_EPOCH_ID + 1n,
        GOLDEN_ENTRIES[0].amount,
      );

      expect(verifyProof(wrongEpoch, tree.proofFor(0), tree.root!)).toBe(false);
    });

    it("looks a proof up by address", () => {
      const tree = buildMerkleTree(GOLDEN_ENTRIES, GOLDEN_EPOCH_ID);

      expect(tree.proofForAddress(GOLDEN_ENTRIES[2].address)).toEqual(GOLDEN_PROOFS[2]);
      expect(tree.proofForAddress("GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF")).toBeNull();
    });

    it("throws for an out-of-range leaf index", () => {
      const tree = buildMerkleTree(GOLDEN_ENTRIES, GOLDEN_EPOCH_ID);

      expect(() => tree.proofFor(GOLDEN_ENTRIES.length)).toThrow(RangeError);
      expect(() => tree.proofFor(-1)).toThrow(RangeError);
    });
  });

  describe("edge cases", () => {
    it("treats a zero-participation epoch as a valid empty tree, not an error", () => {
      const tree = buildMerkleTree([], GOLDEN_EPOCH_ID);

      expect(tree.root).toBeNull();
      expect(tree.entries).toEqual([]);
      expect(tree.leaves).toEqual([]);
      expect(tree.proofForAddress(GOLDEN_ENTRIES[0].address)).toBeNull();
    });

    it("gives a single-leaf tree the leaf as its root and an empty proof", () => {
      const tree = buildMerkleTree([GOLDEN_ENTRIES[0]], GOLDEN_EPOCH_ID);

      expect(tree.root).toBe(GOLDEN_LEAVES[0]);
      expect(tree.proofFor(0)).toEqual([]);
      expect(verifyProof(Buffer.from(GOLDEN_LEAVES[0], "hex"), [], tree.root!)).toBe(true);
    });

    it("sorts each pair before hashing, so sibling order cannot change a node", () => {
      const a = Buffer.from(GOLDEN_LEAVES[0], "hex");
      const b = Buffer.from(GOLDEN_LEAVES[1], "hex");

      expect(hashPair(a, b).toString("hex")).toBe(hashPair(b, a).toString("hex"));
    });
  });
});
